#cd awdmnlkamndklmakdmlkamn wwdm,malkdmn lkamnwkljImagen base
FROM debian:bookworm-slim

#Evitar preguntas interactivas
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
bash \
php-fpm \
php-mysql \
php-cli \
php-curl \
php-gd \
php-mbstring \
php-xml \
php-zip \
curl \
ca-certificates \
&& rm -rf /var/lib/apt/lists/*

COPY conf/www.conf /etc/php/8.2/pool.d/www.conf
#Copia y reemplaza la configuracion por defecto de PHP

COPY tools/setup_wp.sh /usr/local/bin/setup_wp.sh
#Copia el script de inicializacion de wordpress

RUN chmod +x /usr/local/bin/setup_wp.sh
#Permisos para la ejecucion del script

WORKDIR /var/www/html
#Directorio donde vivirá wordpress

EXPOSE 9000
#Puerto interno de escucha en la red virtual de docker para PHP

ENTRYPOINT ["/usr/local/bin/setup_wp.sh"]
#Script que se ejecuta  al lanzar (PID 1)
